# fly.toml app configuration file generated for bold-shape-3821 on 2023-08-28T13:19:00-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-shape-3821"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

# [services.concurrency]
#     type = "connections"
#     hard_limit = 1
#     soft_limit = 1